CREATE TABLE users (
  user_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR2(80)  NOT NULL,
  email       VARCHAR2(200) NOT NULL,
  nationality VARCHAR2(40),
  nickname    VARCHAR2(40),
  language    VARCHAR2(20),
  created_at  DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE categories (
  category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR2(60)  NOT NULL,
  description VARCHAR2(400),
  CONSTRAINT uq_categories_name UNIQUE (name)
);

CREATE TABLE venues (
  venue_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name     VARCHAR2(80) NOT NULL,
  campus   VARCHAR2(60),
  building VARCHAR2(60),
  room     VARCHAR2(40),
  map_url  VARCHAR2(500)
);

-- 2) CHILD TABLES
CREATE TABLE clubs (
  club_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            VARCHAR2(60) NOT NULL,
  club_type       VARCHAR2(20),
  description     VARCHAR2(1000),
  created_at      DATE DEFAULT SYSDATE NOT NULL,
  status          VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL,
  main_image_url  VARCHAR2(500),
  contact_info    VARCHAR2(200),
  creator_user_id NUMBER NOT NULL,
  category_id     NUMBER NOT NULL,
  CONSTRAINT fk_clubs_user     FOREIGN KEY (creator_user_id) REFERENCES users(user_id),
  CONSTRAINT fk_clubs_category FOREIGN KEY (category_id)     REFERENCES categories(category_id),
  CONSTRAINT chk_clubs_status  CHECK (status IN ('ACTIVE','INACTIVE','ARCHIVED'))
);
CREATE INDEX idx_clubs_user     ON clubs(creator_user_id);
CREATE INDEX idx_clubs_category ON clubs(category_id);

CREATE TABLE events (
  event_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id    NUMBER NOT NULL,
  venue_id   NUMBER NOT NULL,
  title      VARCHAR2(100) NOT NULL,
  summary    VARCHAR2(1000),
  start_time DATE NOT NULL,
  end_time   DATE NOT NULL,
  language   VARCHAR2(20),
  capacity   NUMBER DEFAULT 0 NOT NULL,
  fee        NUMBER(10,2) DEFAULT 0 NOT NULL,
  status     VARCHAR2(12) DEFAULT 'SCHEDULED' NOT NULL,
  created_at DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT fk_events_club   FOREIGN KEY (club_id)  REFERENCES clubs(club_id),
  CONSTRAINT fk_events_venue  FOREIGN KEY (venue_id) REFERENCES venues(venue_id),
  CONSTRAINT chk_events_times    CHECK (end_time > start_time),
  CONSTRAINT chk_events_capacity CHECK (capacity >= 0),
  CONSTRAINT chk_events_fee      CHECK (fee >= 0),
  CONSTRAINT chk_events_status   CHECK (status IN ('SCHEDULED','CANCELLED','COMPLETED','POSTPONED'))
);
CREATE INDEX idx_events_club   ON events(club_id);
CREATE INDEX idx_events_venue  ON events(venue_id);
CREATE INDEX idx_events_start  ON events(start_time);

CREATE TABLE memberships (
  membership_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       NUMBER NOT NULL,
  club_id       NUMBER NOT NULL,
  role          VARCHAR2(20) DEFAULT 'MEMBER' NOT NULL,
  joined_at     DATE DEFAULT SYSDATE NOT NULL,
  left_at       DATE,
  status        VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT fk_memberships_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
  CONSTRAINT fk_memberships_club FOREIGN KEY (club_id) REFERENCES clubs(club_id) ON DELETE CASCADE,
  CONSTRAINT uq_memberships_user_club UNIQUE (user_id, club_id),
  CONSTRAINT chk_memberships_dates  CHECK (left_at IS NULL OR left_at > joined_at),
  CONSTRAINT chk_memberships_status CHECK (status IN ('ACTIVE','LEFT','BANNED'))
);
CREATE INDEX idx_memberships_user ON memberships(user_id);
CREATE INDEX idx_memberships_club ON memberships(club_id);

CREATE TABLE registrations (
  registration_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       NUMBER NOT NULL,
  event_id      NUMBER NOT NULL,
  registered_at DATE DEFAULT SYSDATE NOT NULL,
  status        VARCHAR2(12) DEFAULT 'PENDING' NOT NULL,
  attended      CHAR(1) DEFAULT 'N' NOT NULL CHECK (attended IN ('Y','N')),
  CONSTRAINT fk_registrations_user  FOREIGN KEY (user_id)  REFERENCES users(user_id)   ON DELETE CASCADE,
  CONSTRAINT fk_registrations_event FOREIGN KEY (event_id) REFERENCES events(event_id) ON DELETE CASCADE,
  CONSTRAINT uq_registrations_user_event UNIQUE (user_id, event_id),
  CONSTRAINT chk_registrations_status CHECK (status IN ('PENDING','CONFIRMED','CANCELLED','WAITLISTED'))
);
CREATE INDEX idx_registrations_user  ON registrations(user_id);
CREATE INDEX idx_registrations_event ON registrations(event_id);

-- 3) REVIEW = EVENT 전용
CREATE TABLE reviews (
  review_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     NUMBER NOT NULL,
  event_id    NUMBER NOT NULL,
  rating      NUMBER(2) NOT NULL,
  review_text VARCHAR2(2000),
  created_at  DATE DEFAULT SYSDATE NOT NULL,
  status      VARCHAR2(12) DEFAULT 'VISIBLE' NOT NULL,
  CONSTRAINT fk_reviews_user   FOREIGN KEY (user_id)  REFERENCES users(user_id)   ON DELETE CASCADE,
  CONSTRAINT fk_reviews_event  FOREIGN KEY (event_id) REFERENCES events(event_id) ON DELETE CASCADE,
  CONSTRAINT chk_reviews_rating CHECK (rating BETWEEN 1 AND 5),
  CONSTRAINT chk_reviews_status CHECK (status IN ('VISIBLE','HIDDEN','FLAGGED'))

);
CREATE INDEX idx_reviews_user  ON reviews(user_id);
CREATE INDEX idx_reviews_event ON reviews(event_id);

COMMIT;
